### ISSUE TITLE
TypeError: Failed to fetch - Error is showing while uploading images to aws

### ISSUE THREAD

**Issue by Afsana1313** [NimperX/react-aws-s3-typescript#6]
I am getting errors while implementing react-aws-s3-typescript. Here is my code - 

`function App() {async function handleImageChange(e: any) {
e.preventDefault();
await getCredentials();
const config = {
  bucketName: "bucketName",
  dirName: "/dirName/Images",
  region: "us-east-1",
  accessKeyId: localStorage.getItem("accessKey"),
  secretAccessKey: localStorage.getItem("secretKey")
};
const s3 = new ReactS3Client(config as IConfig);
let uploadedFile = e.target.files[0];
  return (
<div className="App">
  <input
    className="select-image-btn"
    type="file"
    onChange={(e) => handleImageChange(e)}
  />
</div>);}`

the Error I am getting is -

`POST https://bucketName.s3-us-east-1.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED`
 and 

`TypeError: Failed to fetch
at ReactS3Client.<anonymous> (react-aws-s3.js:92:1)
at step (react-aws-s3.js:44:1)
at Object.next (react-aws-s3.js:25:1)
at react-aws-s3.js:19:1
at new Promise (<anonymous>)
at __webpack_modules__../node_modules/react-aws-s3-typescript/dist/react-aws-s3.js.__awaiter (react-aws-s3.js:15:1)
at ReactS3Client.uploadFile (react-aws-s3.js:65:1)
at handleImageChange (App.tsx:27:1)`

I am unable to understand the reason for the error shown in the console. Can anyone help me in understanding the problem?

**Comment by NimperX** [comment]
Hi @Afsana1313 ,

Have you created a bucket in your AWS account? if yes, please replace `"bucketName"` in the config object with your bucket name. Otherwise, create a S3 bucket to store files and then replace the bucket name in the config object

**Comment by Afsana1313** [comment]
Hi NimperX,
I had an account. For privacy, I hid the bucket name.

**Comment by NimperX** [comment]
@Afsana1313 If you have set the correct permissions for the bucket, then you will get following screen when go to `https://bucketName.s3-us-east-1.amazonaws.com/` in your web browser.
![image](https://user-images.githubusercontent.com/16362839/185777846-e1ce8f72-41b6-4058-839d-885599eb21be.png)

**Comment by jainesh2906** [comment]
I have provided the bucketName in the config object but still I am getting failed to fetch error while uploading image or video on the s3

**Comment by Afsana1313** [comment]
@jainesh2906 , Please double check your actual s3url if it is valid or not, the service you are using provided from aws, if you need to use any encrypted data

**Comment by NimperX** [comment]
@jainesh2906 Is this fixed? If yes, please acknowledge.
